name-template: '${{ tag_name }}'
tag-template: ''

# μλ™ μƒμ„±λ λ¦΄λ¦¬μ¤ λ…ΈνΈμ— changelog.md λ§ν¬ μ¶”κ°€
template: |
  π‘‰ [**μμ„Έν• λ³€κ²½ μ‚¬ν•­μ€ changelog.mdμ—μ„ ν™•μΈν•μ„Έμ”**](https://github.com/${{ repo }}/blob/${{ tag_name }}/changelog.md)
